name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Build application
      run: |
        # Create build directory and copy all necessary files
        mkdir -p build
        # Copy root index.html
        cp index.html build/
        # Copy all public files
        cp -r public build/
        # Copy any additional assets
        if [ -d "assets" ]; then
          cp -r assets build/
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build